insert into public.menu_categories (normalized_key, original_label, source_language, target_language, translated_label)
values
  ('american', 'American', 'en', 'en', 'American Cuisine'),
  ('american', 'American', 'en', 'zh', '美国菜'),
  ('american', 'American', 'en', 'zh-Hant', '美國菜'),
  ('american', 'American', 'en', 'es', 'Cocina estadounidense'),
  ('chinese', 'Chinese', 'en', 'en', 'Chinese Cuisine'),
  ('chinese', 'Chinese', 'en', 'zh', '中国菜'),
  ('chinese', 'Chinese', 'en', 'zh-Hant', '中國菜'),
  ('chinese', 'Chinese', 'en', 'es', 'Cocina china'),
  ('french', 'French', 'en', 'en', 'French Cuisine'),
  ('french', 'French', 'en', 'zh', '法国菜'),
  ('french', 'French', 'en', 'zh-Hant', '法國菜'),
  ('french', 'French', 'en', 'es', 'Cocina francesa'),
  ('indian', 'Indian', 'en', 'en', 'Indian Cuisine'),
  ('indian', 'Indian', 'en', 'zh', '印度菜'),
  ('indian', 'Indian', 'en', 'zh-Hant', '印度菜'),
  ('indian', 'Indian', 'en', 'es', 'Cocina india'),
  ('italian', 'Italian', 'en', 'en', 'Italian Cuisine'),
  ('italian', 'Italian', 'en', 'zh', '意大利菜'),
  ('italian', 'Italian', 'en', 'zh-Hant', '義大利菜'),
  ('italian', 'Italian', 'en', 'es', 'Cocina italiana'),
  ('japanese', 'Japanese', 'en', 'en', 'Japanese Cuisine'),
  ('japanese', 'Japanese', 'en', 'zh', '日本料理'),
  ('japanese', 'Japanese', 'en', 'zh-Hant', '日本料理'),
  ('japanese', 'Japanese', 'en', 'es', 'Cocina japonesa'),
  ('korean', 'Korean', 'en', 'en', 'Korean Cuisine'),
  ('korean', 'Korean', 'en', 'zh', '韩国料理'),
  ('korean', 'Korean', 'en', 'zh-Hant', '韓國料理'),
  ('korean', 'Korean', 'en', 'es', 'Cocina coreana'),
  ('mexican', 'Mexican', 'en', 'en', 'Mexican Cuisine'),
  ('mexican', 'Mexican', 'en', 'zh', '墨西哥菜'),
  ('mexican', 'Mexican', 'en', 'zh-Hant', '墨西哥菜'),
  ('mexican', 'Mexican', 'en', 'es', 'Cocina mexicana'),
  ('spanish', 'Spanish', 'en', 'en', 'Spanish Cuisine'),
  ('spanish', 'Spanish', 'en', 'zh', '西班牙菜'),
  ('spanish', 'Spanish', 'en', 'zh-Hant', '西班牙菜'),
  ('spanish', 'Spanish', 'en', 'es', 'Cocina española'),
  ('thai', 'Thai', 'en', 'en', 'Thai Cuisine'),
  ('thai', 'Thai', 'en', 'zh', '泰国菜'),
  ('thai', 'Thai', 'en', 'zh-Hant', '泰國菜'),
  ('thai', 'Thai', 'en', 'es', 'Cocina tailandesa'),
  ('vietnamese', 'Vietnamese', 'en', 'en', 'Vietnamese Cuisine'),
  ('vietnamese', 'Vietnamese', 'en', 'zh', '越南菜'),
  ('vietnamese', 'Vietnamese', 'en', 'zh-Hant', '越南菜'),
  ('vietnamese', 'Vietnamese', 'en', 'es', 'Cocina vietnamita')
on conflict (normalized_key, original_label, target_language) do update
set source_language = excluded.source_language,
    translated_label = excluded.translated_label,
    updated_at = now();
