


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."ensure_dish_cache_normalized_name"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if new.normalized_name is null
     or btrim(new.normalized_name) = ''
     or lower(btrim(new.normalized_name)) in ('empty', 'unknown', 'none', 'null', 'undefined', 'n/a', 'na') then
    new.normalized_name := lower(btrim(coalesce(nullif(btrim(new.original_name), ''), nullif(btrim(new.translated_name), ''))));
  else
    new.normalized_name := lower(btrim(new.normalized_name));
  end if;

  if new.normalized_name is null
     or btrim(new.normalized_name) = ''
     or lower(btrim(new.normalized_name)) in ('empty', 'unknown', 'none', 'null', 'undefined', 'n/a', 'na') then
    raise exception 'dish_cache.normalized_name cannot be empty or a placeholder';
  end if;

  return new;
end;
$$;


ALTER FUNCTION "public"."ensure_dish_cache_normalized_name"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."ensure_dish_images_normalized_name"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if new.normalized_name is null
     or btrim(new.normalized_name) = ''
     or lower(btrim(new.normalized_name)) in ('empty', 'unknown', 'none', 'null', 'undefined', 'n/a', 'na') then
    new.normalized_name := lower(btrim(coalesce(nullif(btrim(new.original_name), ''), nullif(btrim(new.image_prompt), ''))));
  else
    new.normalized_name := lower(btrim(new.normalized_name));
  end if;

  if new.normalized_name is null
     or btrim(new.normalized_name) = ''
     or lower(btrim(new.normalized_name)) in ('empty', 'unknown', 'none', 'null', 'undefined', 'n/a', 'na') then
    raise exception 'dish_images.normalized_name cannot be empty or a placeholder';
  end if;

  return new;
end;
$$;


ALTER FUNCTION "public"."ensure_dish_images_normalized_name"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_config_entries" (
    "id" bigint NOT NULL,
    "namespace" "text" NOT NULL,
    "key" "text" NOT NULL,
    "value" "jsonb" NOT NULL,
    "description" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "app_config_entries_key_not_blank" CHECK (("btrim"("key") <> ''::"text")),
    CONSTRAINT "app_config_entries_namespace_not_blank" CHECK (("btrim"("namespace") <> ''::"text"))
);


ALTER TABLE "public"."app_config_entries" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."app_config_entries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."app_config_entries_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."app_config_entries_id_seq" OWNED BY "public"."app_config_entries"."id";



CREATE TABLE IF NOT EXISTS "public"."dish_cache" (
    "id" bigint NOT NULL,
    "normalized_name" "text" NOT NULL,
    "original_name" "text",
    "source_language" "text",
    "target_language" "text" NOT NULL,
    "translated_name" "text",
    "description" "text",
    "ingredients" "jsonb" DEFAULT '[]'::"jsonb",
    "allergens" "jsonb" DEFAULT '[]'::"jsonb",
    "spicy_level" integer DEFAULT 0,
    "image_prompt" "text",
    "cuisine" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "dish_cache_normalized_name_not_blank" CHECK ((("btrim"("normalized_name") <> ''::"text") AND ("lower"("btrim"("normalized_name")) <> ALL (ARRAY['empty'::"text", 'unknown'::"text", 'none'::"text", 'null'::"text", 'undefined'::"text", 'n/a'::"text", 'na'::"text"]))))
);


ALTER TABLE "public"."dish_cache" OWNER TO "postgres";


ALTER TABLE "public"."dish_cache" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dish_cache_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dish_images" (
    "id" bigint NOT NULL,
    "normalized_name" "text" NOT NULL,
    "original_name" "text",
    "cuisine" "text",
    "image_url" "text",
    "local_image_path" "text",
    "thumbnail_url" "text",
    "image_prompt" "text",
    "source_type" "text" DEFAULT 'preset'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "rejected_urls" "jsonb" DEFAULT '[]'::"jsonb",
    CONSTRAINT "dish_images_normalized_name_not_blank" CHECK ((("btrim"("normalized_name") <> ''::"text") AND ("lower"("btrim"("normalized_name")) <> ALL (ARRAY['empty'::"text", 'unknown'::"text", 'none'::"text", 'null'::"text", 'undefined'::"text", 'n/a'::"text", 'na'::"text"]))))
);


ALTER TABLE "public"."dish_images" OWNER TO "postgres";


ALTER TABLE "public"."dish_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dish_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."menu_categories" (
    "id" integer NOT NULL,
    "normalized_key" "text" NOT NULL,
    "original_label" "text" NOT NULL,
    "source_language" "text",
    "target_language" "text" NOT NULL,
    "translated_label" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."menu_categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."menu_categories_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."menu_categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."menu_categories_id_seq" OWNED BY "public"."menu_categories"."id";



CREATE TABLE IF NOT EXISTS "public"."menu_parse_cache" (
    "id" bigint NOT NULL,
    "image_hash" "text" NOT NULL,
    "target_language" "text" NOT NULL,
    "source_language" "text",
    "restaurant_type" "text",
    "ocr_blocks" "jsonb",
    "structure_result" "jsonb",
    "menu_items" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "business_name" "text",
    "business_description" "jsonb",
    "currency" "text"
);


ALTER TABLE "public"."menu_parse_cache" OWNER TO "postgres";


ALTER TABLE "public"."menu_parse_cache" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."menu_parse_cache_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."noise_keywords" (
    "id" integer NOT NULL,
    "keyword" "text" NOT NULL,
    "source_language" "text"
);


ALTER TABLE "public"."noise_keywords" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."noise_keywords_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."noise_keywords_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."noise_keywords_id_seq" OWNED BY "public"."noise_keywords"."id";



CREATE TABLE IF NOT EXISTS "public"."supported_languages" (
    "code" "text" NOT NULL,
    "english_name" "text" NOT NULL,
    "native_name" "text" NOT NULL,
    "family" "text" NOT NULL,
    "google_code" "text" NOT NULL,
    "ocr_code" "text",
    "enabled_source" boolean DEFAULT true NOT NULL,
    "enabled_target" boolean DEFAULT true NOT NULL,
    "display_order" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."supported_languages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."translation_glossary_terms" (
    "id" integer NOT NULL,
    "source_text" "text" NOT NULL,
    "source_language" "text",
    "target_language" "text" NOT NULL,
    "translated_text" "text" NOT NULL,
    "context" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."translation_glossary_terms" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."translation_glossary_terms_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."translation_glossary_terms_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."translation_glossary_terms_id_seq" OWNED BY "public"."translation_glossary_terms"."id";



CREATE TABLE IF NOT EXISTS "public"."unit_translations" (
    "id" integer NOT NULL,
    "source_unit" character varying(50) NOT NULL,
    "target_lang" character varying(10) NOT NULL,
    "translated_unit" character varying(100) NOT NULL,
    "source_language" "text"
);


ALTER TABLE "public"."unit_translations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."unit_translations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."unit_translations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."unit_translations_id_seq" OWNED BY "public"."unit_translations"."id";



CREATE TABLE IF NOT EXISTS "public"."user_cart_state" (
    "user_id" "text" NOT NULL,
    "items" "jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."user_cart_state" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_menu_history" (
    "id" bigint NOT NULL,
    "user_id" "text" NOT NULL,
    "menu_hash" "text",
    "source_uri" "text",
    "target_language" "text",
    "source_language" "text",
    "business_name" "text",
    "restaurant_type" "text",
    "currency" "text",
    "menu_result" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."user_menu_history" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_menu_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_menu_history_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_menu_history_id_seq" OWNED BY "public"."user_menu_history"."id";



CREATE TABLE IF NOT EXISTS "public"."user_subscriptions" (
    "id" bigint NOT NULL,
    "user_id" "text" NOT NULL,
    "plan" "text" NOT NULL,
    "status" "text" NOT NULL,
    "is_expired" boolean NOT NULL,
    "expired_at" timestamp with time zone,
    "stripe_customer_id" "text",
    "stripe_subscription_id" "text",
    "purchase_token" "text",
    "original_transaction_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "store_type" "text",
    "membership_level" "text" DEFAULT 'free'::"text" NOT NULL,
    CONSTRAINT "chk_membership_level" CHECK (("membership_level" = ANY (ARRAY['free'::"text", 'premium'::"text", 'pro'::"text"]))),
    CONSTRAINT "chk_plan_values" CHECK (("plan" = ANY (ARRAY['free'::"text", 'premium'::"text", 'pro'::"text"])))
);


ALTER TABLE "public"."user_subscriptions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_subscriptions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_subscriptions_id_seq" OWNED BY "public"."user_subscriptions"."id";



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "text" NOT NULL,
    "username" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text",
    "avatar_url" "text",
    "diets" "jsonb",
    "allergies" "jsonb",
    "budget" "text",
    "taste" "text",
    "preferred_language" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "role" "text" DEFAULT 'normal'::"text",
    CONSTRAINT "chk_user_role" CHECK (("role" = ANY (ARRAY['super user'::"text", 'admin'::"text", 'normal'::"text"])))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."app_config_entries" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."app_config_entries_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."menu_categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."menu_categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."noise_keywords" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."noise_keywords_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."translation_glossary_terms" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."translation_glossary_terms_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."unit_translations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."unit_translations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_menu_history" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_menu_history_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_subscriptions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_subscriptions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."app_config_entries"
    ADD CONSTRAINT "app_config_entries_namespace_key_uc" UNIQUE ("namespace", "key");



ALTER TABLE ONLY "public"."app_config_entries"
    ADD CONSTRAINT "app_config_entries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dish_cache"
    ADD CONSTRAINT "dish_cache_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dish_cache"
    ADD CONSTRAINT "dish_cache_unique_name_lang" UNIQUE ("normalized_name", "target_language");



ALTER TABLE ONLY "public"."dish_images"
    ADD CONSTRAINT "dish_images_normalized_name_key" UNIQUE ("normalized_name");



ALTER TABLE ONLY "public"."dish_images"
    ADD CONSTRAINT "dish_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_categories"
    ADD CONSTRAINT "menu_categories_normalized_key_original_label_target_lang_uc" UNIQUE ("normalized_key", "original_label", "target_language");



ALTER TABLE ONLY "public"."menu_categories"
    ADD CONSTRAINT "menu_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_parse_cache"
    ADD CONSTRAINT "menu_parse_cache_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_parse_cache"
    ADD CONSTRAINT "menu_parse_cache_unique_hash_lang" UNIQUE ("image_hash", "target_language");



ALTER TABLE ONLY "public"."noise_keywords"
    ADD CONSTRAINT "noise_keywords_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."supported_languages"
    ADD CONSTRAINT "supported_languages_pkey" PRIMARY KEY ("code");



ALTER TABLE ONLY "public"."translation_glossary_terms"
    ADD CONSTRAINT "translation_glossary_terms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."translation_glossary_terms"
    ADD CONSTRAINT "translation_glossary_terms_source_target_uc" UNIQUE ("source_text", "source_language", "target_language");



ALTER TABLE ONLY "public"."unit_translations"
    ADD CONSTRAINT "unit_translations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_cart_state"
    ADD CONSTRAINT "user_cart_state_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."user_menu_history"
    ADD CONSTRAINT "user_menu_history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_menu_history"
    ADD CONSTRAINT "user_menu_history_user_hash_target_uc" UNIQUE ("user_id", "menu_hash", "target_language");



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



CREATE INDEX "app_config_entries_namespace_active_idx" ON "public"."app_config_entries" USING "btree" ("namespace", "is_active");



CREATE INDEX "idx_dish_cache_normalized_name" ON "public"."dish_cache" USING "btree" ("normalized_name");



CREATE INDEX "idx_dish_cache_target_language" ON "public"."dish_cache" USING "btree" ("target_language");



CREATE INDEX "idx_dish_images_normalized_name" ON "public"."dish_images" USING "btree" ("normalized_name");



CREATE INDEX "idx_menu_parse_cache_image_hash" ON "public"."menu_parse_cache" USING "btree" ("image_hash");



CREATE INDEX "ix_noise_keywords_id" ON "public"."noise_keywords" USING "btree" ("id");



CREATE INDEX "ix_translation_glossary_terms_id" ON "public"."translation_glossary_terms" USING "btree" ("id");



CREATE INDEX "ix_user_menu_history_id" ON "public"."user_menu_history" USING "btree" ("id");



CREATE INDEX "ix_user_menu_history_menu_hash" ON "public"."user_menu_history" USING "btree" ("menu_hash");



CREATE INDEX "ix_user_menu_history_user_id" ON "public"."user_menu_history" USING "btree" ("user_id");



CREATE INDEX "ix_user_subscriptions_id" ON "public"."user_subscriptions" USING "btree" ("id");



CREATE INDEX "ix_users_id" ON "public"."users" USING "btree" ("id");



CREATE UNIQUE INDEX "noise_keywords_source_keyword_idx" ON "public"."noise_keywords" USING "btree" (COALESCE("source_language", ''::"text"), "lower"("keyword"));



CREATE UNIQUE INDEX "unit_translations_source_target_idx" ON "public"."unit_translations" USING "btree" (COALESCE("source_language", ''::"text"), "lower"(("source_unit")::"text"), "target_lang");



CREATE OR REPLACE TRIGGER "trg_ensure_dish_cache_normalized_name" BEFORE INSERT OR UPDATE OF "normalized_name", "original_name", "translated_name" ON "public"."dish_cache" FOR EACH ROW EXECUTE FUNCTION "public"."ensure_dish_cache_normalized_name"();



CREATE OR REPLACE TRIGGER "trg_ensure_dish_images_normalized_name" BEFORE INSERT OR UPDATE OF "normalized_name", "original_name", "image_prompt" ON "public"."dish_images" FOR EACH ROW EXECUTE FUNCTION "public"."ensure_dish_images_normalized_name"();



ALTER TABLE ONLY "public"."user_cart_state"
    ADD CONSTRAINT "user_cart_state_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_menu_history"
    ADD CONSTRAINT "user_menu_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE "public"."app_config_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dish_cache" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dish_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_parse_cache" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."noise_keywords" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."supported_languages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."translation_glossary_terms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."unit_translations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_cart_state" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_menu_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."ensure_dish_cache_normalized_name"() TO "anon";
GRANT ALL ON FUNCTION "public"."ensure_dish_cache_normalized_name"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."ensure_dish_cache_normalized_name"() TO "service_role";



GRANT ALL ON FUNCTION "public"."ensure_dish_images_normalized_name"() TO "anon";
GRANT ALL ON FUNCTION "public"."ensure_dish_images_normalized_name"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."ensure_dish_images_normalized_name"() TO "service_role";



GRANT ALL ON TABLE "public"."app_config_entries" TO "anon";
GRANT ALL ON TABLE "public"."app_config_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."app_config_entries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_config_entries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_config_entries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_config_entries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dish_cache" TO "anon";
GRANT ALL ON TABLE "public"."dish_cache" TO "authenticated";
GRANT ALL ON TABLE "public"."dish_cache" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dish_cache_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dish_cache_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dish_cache_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dish_images" TO "anon";
GRANT ALL ON TABLE "public"."dish_images" TO "authenticated";
GRANT ALL ON TABLE "public"."dish_images" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dish_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dish_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dish_images_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."menu_categories" TO "anon";
GRANT ALL ON TABLE "public"."menu_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."menu_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."menu_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."menu_categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."menu_parse_cache" TO "anon";
GRANT ALL ON TABLE "public"."menu_parse_cache" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_parse_cache" TO "service_role";



GRANT ALL ON SEQUENCE "public"."menu_parse_cache_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."menu_parse_cache_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."menu_parse_cache_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."noise_keywords" TO "anon";
GRANT ALL ON TABLE "public"."noise_keywords" TO "authenticated";
GRANT ALL ON TABLE "public"."noise_keywords" TO "service_role";



GRANT ALL ON SEQUENCE "public"."noise_keywords_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."noise_keywords_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."noise_keywords_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."supported_languages" TO "anon";
GRANT ALL ON TABLE "public"."supported_languages" TO "authenticated";
GRANT ALL ON TABLE "public"."supported_languages" TO "service_role";



GRANT ALL ON TABLE "public"."translation_glossary_terms" TO "anon";
GRANT ALL ON TABLE "public"."translation_glossary_terms" TO "authenticated";
GRANT ALL ON TABLE "public"."translation_glossary_terms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."translation_glossary_terms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."translation_glossary_terms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."translation_glossary_terms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."unit_translations" TO "anon";
GRANT ALL ON TABLE "public"."unit_translations" TO "authenticated";
GRANT ALL ON TABLE "public"."unit_translations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."unit_translations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."unit_translations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."unit_translations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_cart_state" TO "anon";
GRANT ALL ON TABLE "public"."user_cart_state" TO "authenticated";
GRANT ALL ON TABLE "public"."user_cart_state" TO "service_role";



GRANT ALL ON TABLE "public"."user_menu_history" TO "anon";
GRANT ALL ON TABLE "public"."user_menu_history" TO "authenticated";
GRANT ALL ON TABLE "public"."user_menu_history" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_menu_history_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_menu_history_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_menu_history_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."user_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."user_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_subscriptions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
