import os
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "google/gemini-2.5-flash-lite")
OPENROUTER_VISION_MODEL = os.getenv("OPENROUTER_VISION_MODEL", "google/gemini-2.5-flash-lite")

GOOGLE_CLOUD_API = os.getenv("GOOGLE_CLOUD_API")
GOOGLE_CLOUD_PROJECT_ID = (
    os.getenv("GOOGLE_CLOUD_PROJECT_ID")
    or os.getenv("GOOGLE_CLOUD_PROJECT")
    or os.getenv("GCLOUD_PROJECT")
)
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION", "global")
GOOGLE_CLOUD_TRANSLATION_GLOSSARY_ID = os.getenv("GOOGLE_CLOUD_TRANSLATION_GLOSSARY_ID")
GOOGLE_CLOUD_TRANSLATION_MODEL = os.getenv("GOOGLE_CLOUD_TRANSLATION_MODEL")
GOOGLE_CLOUD_ACCESS_TOKEN = os.getenv("GOOGLE_CLOUD_ACCESS_TOKEN")
GOOGLE_APPLICATION_CREDENTIALS_JSON = (
    os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
    or os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON")
)
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

if not OPENROUTER_API_KEY:
    raise RuntimeError("OPENROUTER_API_KEY is missing")
